# Generated by Django 3.0.3 on 2020-02-18 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='groupadmins',
            new_name='userregistration',
        ),
    ]
