# Generated by Django 3.0.3 on 2020-02-19 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20200217_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='designation',
            field=models.CharField(default='nothing', max_length=20),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='experience',
            field=models.CharField(default='nothing', max_length=20),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='pincode',
            field=models.CharField(default='nothing', max_length=20),
        ),
    ]
