# Generated by Django 3.0.3 on 2020-02-20 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_auto_20200219_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregistration',
            old_name='firstname',
            new_name='fname',
        ),
    ]
