# Generated by Django 3.0.3 on 2020-02-21 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_auto_20200219_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='addqueryUSER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=20)),
                ('addquery', models.CharField(max_length=20)),
                ('fileupload', models.FileField(upload_to='')),
                ('group', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.userregistration_tb')),
            ],
        ),
    ]
