# Generated by Django 3.0.3 on 2020-02-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_auto_20200220_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addqueryuser_tb',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
