# Generated by Django 3.0.3 on 2020-03-11 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GroupAdmin', '0003_delete_queryallocation'),
        ('Users', '0008_auto_20200224_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='usercomplaints_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(default='nothing', max_length=20)),
                ('details', models.CharField(default='nothing', max_length=20)),
                ('date', models.CharField(default='nothing', max_length=20)),
                ('mentor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GroupAdmin.mentorsregistration')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.userregistration_tb')),
            ],
        ),
        migrations.CreateModel(
            name='reply_mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.CharField(max_length=20)),
                ('fileupload', models.FileField(upload_to='')),
                ('date', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('mentor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GroupAdmin.mentorsregistration')),
                ('query_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.addqueryUSER_tb')),
            ],
        ),
        migrations.CreateModel(
            name='QueryAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
                ('mentorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GroupAdmin.mentorsregistration')),
                ('queryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.addqueryUSER_tb')),
            ],
        ),
    ]
