# Generated by Django 3.0.3 on 2020-02-14 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SiteAdmin', '0004_auto_20200212_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='mentorsregistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentorname', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('emailid', models.CharField(max_length=20)),
                ('phoneno', models.CharField(max_length=20)),
                ('qualification', models.CharField(max_length=20)),
                ('experience', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('grpadmin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SiteAdmin.groupadmins')),
            ],
        ),
    ]
