# Generated by Django 3.0.3 on 2020-02-24 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_auto_20200224_1225'),
        ('GroupAdmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
                ('mentorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GroupAdmin.mentorsregistration')),
                ('queryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.addqueryUSER_tb')),
            ],
        ),
    ]
