# Generated by Django 3.0.3 on 2020-03-11 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GroupAdmin', '0002_queryallocation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QueryAllocation',
        ),
    ]
