# Generated by Django 3.0.3 on 2020-03-11 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mentors', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='reply_mentor',
        ),
    ]
