# Generated by Django 3.0.3 on 2020-03-14 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteAdmin', '0004_auto_20200212_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='expectedchisquare_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_chi_value', models.CharField(max_length=20)),
                ('groupname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='p1_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v1', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='pattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patternname', models.CharField(max_length=20)),
            ],
        ),
    ]
